In [1]:
import numpy as np

In [7]:
arr= np.array([[1,2,4,2,5,6]], np.int8) # np.int8 means 8 bit num or np.int32 means 32bit and soo onn

In [4]:
arr

array([1, 2, 4, 2, 5, 6], dtype=int8)

In [5]:
arr[0]

1

In [8]:
arr[0,2]

4

In [9]:
arr.shape

(1, 6)

In [10]:
arr.dtype

dtype('int8')

In [11]:
arr[0,2] = 7 # Changing element

In [12]:
arr

array([[1, 2, 7, 2, 5, 6]], dtype=int8)

In [14]:
listarray = np.array([[1,2,34,3],[33,2,4,1],[4,3,1,32]])

In [19]:
listarray.dtype

dtype('int32')

In [16]:
listarray

array([[ 1,  2, 34,  3],
       [33,  2,  4,  1],
       [ 4,  3,  1, 32]])

In [17]:
listarray.size

12

In [18]:
listarray.shape

(3, 4)

In [20]:
arr2 = np.array({1,2,4})

In [21]:
arr2

array({1, 2, 4}, dtype=object)

In [25]:
zeros = np.zeros((3,3)) # create 3by3 matrices of zeros

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
rng = np.arange(11)

In [28]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
lspace = np.linspace(1,6,9) # give 9 elements from 1 t0 6 of equal linear spacing

In [32]:
lspace

array([1.   , 1.625, 2.25 , 2.875, 3.5  , 4.125, 4.75 , 5.375, 6.   ])

In [39]:
emp = np.empty((4,4))

In [40]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.29060871e-306,
        6.23059386e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [45]:
lemp = np.empty_like(lspace)

In [46]:
lemp

array([1.   , 1.625, 2.25 , 2.875, 3.5  , 4.125, 4.75 , 5.375, 6.   ])

In [49]:
ide = np.identity(3)

In [50]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
qqw = np.arange(1,10)

In [55]:
qqw

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
qwq = qqw.reshape(3,3) # change into 3By3

In [57]:
qwq

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
qwq = qwq.ravel() # convert 1 d array

In [59]:
qwq

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
qwq.shape

(9,)

In [61]:
aaa = np.array(([1,2,3],[4,5,6],[7,0,1]))

In [62]:
aaa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [63]:
aaa.sum()

29

In [64]:
aaa.sum(axis=0)

array([12,  7, 10])

In [65]:
aaa.sum(axis=1)

array([ 6, 15,  8])

In [68]:
aaa.T # transpore matrix

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [70]:
aaa.flat # help for running loop

In [71]:
for items in aaa.flat:
    print(items)

1
2
3
4
5
6
7
0
1


In [72]:
aaa.ndim # shows dimension

2

In [73]:
aaa.size

9

In [75]:
aaa.nbytes # it shows how much byte your array consume

36

In [76]:
a1 = np.array([1,2,3,11]) 

In [77]:
a1.argmax() # it show index of maximum element

3

In [78]:
a1.argmin() # it shows index of minimum element

0

In [79]:
a1.argsort() # it shows index which help in sorting array

array([0, 1, 2, 3], dtype=int64)

In [80]:
aaa.argmin()

7

In [81]:
aaa.argmax()

6

In [82]:
aaa.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [83]:
aaa.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [84]:
aaa.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [85]:
aaa.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [86]:
aaa.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [87]:
aaa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [88]:
aaa.ravel()

array([1, 2, 3, 4, 5, 6, 7, 0, 1])

In [89]:
aaa.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [0],
       [1]])

In [90]:
aaa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [91]:
aaa2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [92]:
aaa2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [93]:
aaa + aaa2


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  0,  2]])

In [94]:
np.sqrt(aaa)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 0.        , 1.        ]])

In [96]:
aaa.sum()

29

In [97]:
aaa.max()

7

In [98]:
aaa.min()

0

In [99]:
aaa


array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [100]:
np.where(aaa>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [102]:
np.count_nonzero(aaa)

8

In [103]:
np.nonzero(aaa)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [104]:
aaa[1,2] = 0

In [106]:
np.nonzero(aaa)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 2], dtype=int64))

In [107]:
import sys
py_ar = [1,2,3,4,5,6]
np_ar = np.array(py_ar)

In [108]:
sys.getsizeof(1) * len(py_ar)

168

In [109]:
np_ar.itemsize * np_ar.size

24